import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./Componen/Navber";

import Footer from "./Componen/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add weights as needed
  variable: "--font-jakarta", // Optional: use as CSS variable
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={plusJakartaSans.className}
      >
        <Navbar/>
        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
